# HKD Multi-Stage Production Container
# Generated by HKD Platform Tooling

# ── Stage 1: Build Environment ──────────────────────────────────────────────────
FROM node:20-alpine AS builder

WORKDIR /build

# Copy dependency manifests first for layer caching
COPY package*.json ./
COPY hkd.toml* hkd.lock* ./

# Copy project source tree
COPY . .

# Compile TypeScript / CLI toolchain and produce native standalone binary
RUN npm ci --ignore-scripts || npm install
RUN npm run build
RUN node dist/cli/main.js build --native --profile release --target x86_64-linux -o /build/target/release/server

# ── Stage 2: Hardened Minimal Runtime ──────────────────────────────────────────
FROM alpine:3.20 AS runtime

# Create dedicated non-root user and group
RUN addgroup -S -g 10001 hkd && \
    adduser -S -u 10001 -G hkd -h /app -s /sbin/nologin hkd

WORKDIR /app

# Copy only the compiled standalone binary from builder stage
COPY --from=builder --chown=hkd:hkd /build/target/release/server /app/server

# Switch to non-root execution
USER hkd:hkd

EXPOSE 8080

# Container healthcheck using built-in /health probe
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget -qO- http://127.0.0.1:8080/health || exit 1

ENTRYPOINT ["/app/server"]
