/**
 * HKD Containerization & Docker Engine
 *
 * Generates multi-stage, hardened Dockerfiles and .dockerignore files,
 * enforcing non-root execution, minimal image layers, and zero secret leakage.
 */

import * as fs from "fs";
import * as path from "path";
import { readManifest } from "../package-manager/index.js";

export interface ContainerConfig {
  port?: number;
  entry?: string;
  target?: string;
  baseImage?: string;
}

export function generateDockerfile(config: ContainerConfig = {}): string {
  const port = config.port || 8080;
  const target = config.target || "x86_64-linux";

  return `# HKD Multi-Stage Production Container
# Generated by HKD Platform Tooling

# ── Stage 1: Build Environment ──────────────────────────────────────────────────
FROM node:20-alpine AS builder

WORKDIR /build

# Copy dependency manifests first for layer caching
COPY package*.json ./
COPY hkd.toml* hkd.lock* ./

# Copy project source tree
COPY . .

# Compile TypeScript / CLI toolchain and produce native standalone binary
RUN npm ci --ignore-scripts || npm install
RUN npm run build
RUN node dist/cli/main.js build --native --profile release --target ${target} -o /build/target/release/server

# ── Stage 2: Hardened Minimal Runtime ──────────────────────────────────────────
FROM alpine:3.20 AS runtime

# Create dedicated non-root user and group
RUN addgroup -S -g 10001 hkd && \\
    adduser -S -u 10001 -G hkd -h /app -s /sbin/nologin hkd

WORKDIR /app

# Copy only the compiled standalone binary from builder stage
COPY --from=builder --chown=hkd:hkd /build/target/release/server /app/server

# Switch to non-root execution
USER hkd:hkd

EXPOSE ${port}

# Container healthcheck using built-in /health probe
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
  CMD wget -qO- http://127.0.0.1:${port}/health || exit 1

ENTRYPOINT ["/app/server"]
`;
}

export function generateDockerignore(): string {
  return `# HKD Docker Ignore
.git/
.github/
.vscode/
node_modules/
dist/
target/
.hkd/
tests/
*.log
*.env*
*.key
*.pem
*.secret
`;
}

export function initContainer(projectDir: string, config: ContainerConfig = {}): { dockerfile: string; dockerignore: string } {
  const manifest = readManifest(projectDir);
  const port = (manifest as any)?.deploy?.port || config.port || 8080;

  const dockerfilePath = path.join(projectDir, "Dockerfile");
  const dockerignorePath = path.join(projectDir, ".dockerignore");

  const dockerfileContent = generateDockerfile({ port, ...config });
  const dockerignoreContent = generateDockerignore();

  fs.writeFileSync(dockerfilePath, dockerfileContent, "utf-8");
  fs.writeFileSync(dockerignorePath, dockerignoreContent, "utf-8");

  return {
    dockerfile: dockerfilePath,
    dockerignore: dockerignorePath,
  };
}
