/**
 * HKD Lockfile V2 Architecture
 *
 * Implements deterministic TOML-based lockfile format, cryptographic checksum
 * verification, source pinning, dependency graph recording, and V1 migration.
 */

import * as fs from "fs";
import * as path from "path";
import * as crypto from "crypto";
import { normalizePackageName } from "./identity.js";

export interface LockedPackage {
  name: string;
  version: string;
  source: string; // "registry", "path:<relPath>", "cache"
  checksum: string; // "sha256:<digest>"
  dependencies: string[]; // ["dep_name dep_version"] sorted alphabetically
}

export interface LockfileV2 {
  version: 2;
  resolver: string;
  packages: LockedPackage[];
}

/**
 * Serializes a LockfileV2 structure into deterministic TOML.
 * Packages and dependencies are sorted alphabetically.
 */
export function serializeLockfileV2(lockfile: LockfileV2): string {
  const lines: string[] = [
    "# This file is automatically generated by HKD. Do not edit manually.",
    "version = 2",
    `resolver = "${lockfile.resolver || "2.0"}"`,
    "",
  ];

  const sortedPkgs = [...lockfile.packages].sort((a, b) => a.name.localeCompare(b.name));

  for (const pkg of sortedPkgs) {
    lines.push("[[package]]");
    lines.push(`name = "${pkg.name}"`);
    lines.push(`version = "${pkg.version}"`);
    lines.push(`source = "${pkg.source}"`);
    lines.push(`checksum = "${pkg.checksum}"`);

    if (pkg.dependencies && pkg.dependencies.length > 0) {
      const sortedDeps = [...pkg.dependencies].sort((a, b) => a.localeCompare(b));
      lines.push("dependencies = [");
      for (const d of sortedDeps) {
        lines.push(`    "${d}",`);
      }
      lines.push("]");
    } else {
      lines.push("dependencies = []");
    }

    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Parses a LockfileV2 TOML string.
 */
export function parseLockfileV2(content: string): LockfileV2 {
  const lines = content.split("\n");
  let version = 2;
  let resolver = "2.0";
  const packages: LockedPackage[] = [];

  let currentPkg: Partial<LockedPackage> | null = null;
  let inDepsList = false;
  let depsBuffer: string[] = [];

  for (const rawLine of lines) {
    const line = rawLine.replace(/#.*$/, "").trim();
    if (!line) continue;

    if (inDepsList) {
      if (line.startsWith("]")) {
        inDepsList = false;
        if (currentPkg) {
          currentPkg.dependencies = depsBuffer;
        }
        depsBuffer = [];
        continue;
      }
      const depMatch = line.match(/^"([^"]+)",?$/);
      if (depMatch) {
        depsBuffer.push(depMatch[1]);
      }
      continue;
    }

    if (line === "[[package]]") {
      if (currentPkg && currentPkg.name && currentPkg.version) {
        packages.push({
          name: normalizePackageName(currentPkg.name),
          version: currentPkg.version,
          source: currentPkg.source || "registry",
          checksum: currentPkg.checksum || "sha256:0000000000000000000000000000000000000000000000000000000000000000",
          dependencies: currentPkg.dependencies || [],
        });
      }
      currentPkg = { dependencies: [] };
      continue;
    }

    const eqIdx = line.indexOf("=");
    if (eqIdx === -1) continue;

    const key = line.slice(0, eqIdx).trim();
    const val = line.slice(eqIdx + 1).trim();

    if (!currentPkg) {
      if (key === "version") version = parseInt(val, 10);
      if (key === "resolver") resolver = val.replace(/"/g, "");
      continue;
    }

    if (key === "name") currentPkg.name = val.replace(/"/g, "");
    if (key === "version") currentPkg.version = val.replace(/"/g, "");
    if (key === "source") currentPkg.source = val.replace(/"/g, "");
    if (key === "checksum") currentPkg.checksum = val.replace(/"/g, "");
    if (key === "dependencies") {
      if (val === "[]") {
        currentPkg.dependencies = [];
      } else if (val.startsWith("[")) {
        inDepsList = true;
        depsBuffer = [];
      }
    }
  }

  if (currentPkg && currentPkg.name && currentPkg.version) {
    packages.push({
      name: normalizePackageName(currentPkg.name),
      version: currentPkg.version,
      source: currentPkg.source || "registry",
      checksum: currentPkg.checksum || "sha256:0000000000000000000000000000000000000000000000000000000000000000",
      dependencies: currentPkg.dependencies || [],
    });
  }

  packages.sort((a, b) => a.name.localeCompare(b.name));

  return {
    version: 2,
    resolver,
    packages,
  };
}

/**
 * Migrates a legacy V1 JSON lockfile into LockfileV2 format.
 */
export function migrateLockfileV1(v1Content: string): LockfileV2 {
  try {
    const data = JSON.parse(v1Content);
    const pkgs: LockedPackage[] = [];

    if (Array.isArray(data.packages)) {
      for (const p of data.packages) {
        if (!p.name || !p.version) continue;
        let source = "registry";
        let checksum = "sha256:0000000000000000000000000000000000000000000000000000000000000000";

        if (p.source) {
          if (typeof p.source === "object") {
            if (p.source.path) source = `path:${p.source.path}`;
            if (p.source.checksum) {
              checksum = p.source.checksum.startsWith("sha256:")
                ? p.source.checksum
                : `sha256:${crypto.createHash("sha256").update(p.source.checksum).digest("hex")}`;
            }
          } else if (typeof p.source === "string") {
            source = p.source;
          }
        }

        const deps: string[] = [];
        if (p.dependencies && typeof p.dependencies === "object") {
          for (const [depName, depVer] of Object.entries(p.dependencies)) {
            deps.push(`${depName} ${depVer}`);
          }
        }

        pkgs.push({
          name: normalizePackageName(p.name),
          version: String(p.version),
          source,
          checksum,
          dependencies: deps.sort((a, b) => a.localeCompare(b)),
        });
      }
    }

    pkgs.sort((a, b) => a.name.localeCompare(b.name));

    return {
      version: 2,
      resolver: "2.0-migrated",
      packages: pkgs,
    };
  } catch (err: any) {
    throw new Error(`Failed to migrate V1 lockfile: ${err.message}`);
  }
}

/**
 * Reads any lockfile (V1 JSON or V2 TOML) from a project directory.
 * If V1 is found, seamlessly migrates it to V2.
 */
export function readLockfile(projectDir: string): LockfileV2 | null {
  const lockPath = path.join(projectDir, "hkd.lock");
  if (!fs.existsSync(lockPath)) return null;

  const content = fs.readFileSync(lockPath, "utf-8").trim();
  if (content.startsWith("{")) {
    // V1 JSON
    const v2 = migrateLockfileV1(content);
    // Write back migrated V2 TOML
    writeLockfile(projectDir, v2);
    return v2;
  }

  return parseLockfileV2(content);
}

/**
 * Writes a LockfileV2 to `hkd.lock` in the project directory.
 */
export function writeLockfile(projectDir: string, lockfile: LockfileV2): void {
  const lockPath = path.join(projectDir, "hkd.lock");
  const toml = serializeLockfileV2(lockfile);
  fs.writeFileSync(lockPath, toml, "utf-8");
}
